config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
  get 'feed' => 'feed#index'
  get 'dashboard' => 'dashboard#index'

  resources :books do
    resources :comments
    resources :trades
  end

  resources :users, path: :user

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :trades, dependent: :delete_all

  accepts_nested_attributes_for :comments

  validates :title, presence: true
  validates :author, presence: true

  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :sender, :class_name => 'User'
  belongs_to :recipient, :class_name => 'User'

  belongs_to :book
  belongs_to :proposed_book, :class_name => 'Book'

  enum status: [:waiting, :approved, :denied]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_create :generate_username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true

  has_many :books
  has_many :trades

  def generate_username
    self.username = self.email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
    redirect_to root_path
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to dashboard_url
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to dashboard_url
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to dashboard_url
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :pagecount, :shared)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @comment = Comment.find(params[:book_id])
  end

  def edit
    @book = Book.find(params[:id])
    @comment = Comment.find(params[:book_id])
  end

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.create(comment_params)

    respond_to do |format|
      format.js
    end
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to dashboard_url
    else
      render 'edit'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:title, :content, :commenter, :approved)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @my_books = current_user.books
    @comments = Comment.where(commenter: current_user.username)
    @users = User.all
    @trades = Trade.all
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
    @books = Book.where(shared: :true)
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  def show
    @trade = Trade.find(params[:id])
  end

  def edit
    @book = Book.find(params[:book_id])
    @trade = Trade.find(params[:id])
  end

  def create
    @book = Book.find(params[:book_id])
    @trade = @book.trades.create(trade_params)

    if @trade.save
      redirect_to dashboard_url
    else
      render 'new'
    end
  end

  def update
    @books = Book.all
    @trade = Trade.find(params[:id])

    if @trade.update(trade_params)
      redirect_to dashboard_url
    else
      render 'edit'
    end
  end
  private
  def trade_params
    params.require(:trade).permit(:recipient_id, :sender_id, :book_id, :proposed_book_id, :status)
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to feed_url
    else
      @books = Book.where(shared: :true)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/trade_helper.rb
module TradeHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :pagecount %><br>
    <%= form.number_field :pagecount %>
  </p>

  <p>
    <%= form.label :shared %><br>
    <%= form.check_box :shared %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_url %>

app/views/books/show.html.erb
<h1>Book</h1>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
        <div class="col-md-12">
          <div class="card mb-4 shadow-sm">
            <div class="card-header"><%= @book.title %></div>
            <div class="card-body">
              <p class="card-text">Written by <b><%= @book.author %></b>.</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted"><%= @book.pagecount %> pages.</small>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

<% unless @book.user == current_user %>
  <%= form_with(model: [ @book, @book.trades.build ], local: true) do |form| %>
    <h4>Want to trade?</h4>
    <%= form.hidden_field :sender_id, value: current_user.id %>
    <%= form.hidden_field :recipient_id, value: @book.user_id %>
    <%= form.hidden_field :status, value: :waiting %>
    <div class="form-group">
      <%= form.collection_select :proposed_book_id, current_user.books.where(shared: :true).order(:title),:id,:title, include_blank: true, :class => 'form-control' %>
      <%= form.submit :class => 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

<h2>Comments</h2>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @book.comments.each do |comment| %>
        <% if comment.approved %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <div class="card-header"><%= comment.title %></div>
              <div class="card-body">
                <p class="card-text"><%= comment.content %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted"><%= comment.commenter %></small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<h4>Unapproved</h4>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @book.comments.each do |comment| %>
        <% unless comment.approved %>
          <% if comment.commenter == current_user.username %>
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <div class="card-header"><%= comment.title %></div>
                <div class="card-body">
                  <p class="card-text"><%= comment.content %></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted"><%= comment.commenter %></small>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="comment"></div>
</div>


<h2>Add a comment:</h2>
<%= form_with(model: [ @book, @book.comments.build ], local: false) do |form| %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %><br>
    <%= form.text_area :content, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :commenter, value: current_user.username %>
    <%= form.hidden_field :approved, value: false %>
  </div>
  <p>
    <%= form.submit :class => 'btn btn-primary' %>
  </p>
<% end %>

<%= link_to 'Back', welcome_index_url %>

app/views/comments/_comment.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm">
    <div class="card-header"><%= @comment.title %></div>
    <div class="card-body">
      <p class="card-text"><%= @comment.content %></p>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted"><%= @comment.commenter %></small>
      </div>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$(".flash_notice").html("Your comment has submitted for approval.")

$(".comment").append("<%= escape_javascript(render(@comment)) %>");

app/views/comments/edit.html.erb
<p>
  <strong><%= @comment.title %></strong> | <%= @comment.commenter %>
</p>

<p>
  <%= @comment.content %>
</p>

<%= form_with model: [@book, @comment], local: true do |form| %>
  <%= form.hidden_field :title %><br>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :commenter %>
  <p>
  <%= form.label :approve? %>
  <%= form.check_box :approved %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/show.html.erb
<p>A comment has been made on your <strong><%= @book.title %></strong> book.</p>

<p>
  <strong><%= @comment.title %></strong> | <%= @comment.commenter %>
</p>

<p>
  <%= @comment.content %>
</p>

<%= link_to 'Back', welcome_index_url %>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<h3><b>Your Books</b></h3>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @my_books.each do |book| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-header"><%= book.title %></div>
            <div class="card-body">
              <p class="card-text">Written by <b><%= book.author %></b>.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Show', book_path(book), :class => "btn btn-sm btn-outline-secondary" %>
                  <%= link_to 'Edit', edit_book_path(book), :class => "btn btn-sm btn-outline-secondary" %>
                  <%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } ,:class => "btn btn-sm btn-outline-secondary" %>
                </div>
                <small class="text-muted"><%= book.pagecount %> pages.</small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= link_to 'Add a new book', new_book_path, :class => "btn btn-outline-success" %>
  </div>
</div>
  <% if @trades.count > 0 %>
    <h3><b>Trades</b></h3>
  <% end %>
  <div class="d-flex bd-highlight">
  <% @trades.where(:recipient_id => current_user.id).each do |trade| %>
    <div class="card m-2" style="width: 18rem;">
      <div class="card-header">Book: <%= @my_books.where(:id => trade.book_id).first.title %></div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Sender: <%= @users.where(:id => trade.sender_id).first.username %></li>
        <li class="list-group-item">Status: <%= trade.status %></li>
        <li class="list-group-item"><%= link_to 'Respond to offer', edit_book_trade_path(trade.book_id, trade) %></li>
      </ul>
    </div>
  <% end %>
  </div>

  <% if @trades.where(:sender_id => current_user.id).count > 0 %>
    <h3><b>Your Offers</b></h3>
  <% end %>

  <div class="d-flex bd-highlight">
  <% @trades.where(:sender_id => current_user.id).each do |trade| %>
    <div class="card m-2" style="width: 18rem;">
      <div class="card-header">You offered for <b><%= @books.where(:id => trade.book_id).first.title %></b></div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">You proposed <b><%= trade.proposed_book.title %></b> book.</li>
        <li class="list-group-item">Recipient: <%= trade.recipient.username %></li>
        <li class="list-group-item">Status: <%= trade.status %></li>
      </ul>
    </div>
  <% end %>
  </div>

<h3><b>Comments Made To Your Books</b></h3>
<table>
  <% @my_books.each do |book| %>
    <% book.comments.each do |comment| %>
    <div class="alert alert-light" role="alert">
      <%= "#{comment.commenter} wrote a comment to your '#{book.title}' book." %> <%= comment.approved ? 'To disapprove:' : 'To approve:' %> <%= link_to 'Click', edit_book_comment_path(comment, book) %>
    </div>
    <% end %>
  <% end %>
</table>

<h3><b>Your Comments</b></h3>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @comments.each do |comment| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-header"><%= comment.title %></div>
            <div class="card-body">
              <p class="card-text"><%= comment.content %></p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted"><%= comment.book.title %> | <%= comment.approved ? 'Approved' : 'Unapproved' %></small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/feed/index.html.erb
<h1>Shared Books</h1>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @books.each do |book| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-header"><%= book.title %></div>
            <div class="card-body">
              <p class="card-text">Written by <b><%= book.author %></b>.</p>
              <p class="card-text"><%= link_to book.user.username, user_path(book.user)%></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Show', book_path(book), :class => "btn btn-sm btn-outline-secondary" %>
                  <button type="button" class="btn btn-sm btn-outline-secondary" disabled><%= book.trades.count > 0 ? 'Has offers' : 'Has no offers'%></button>
                </div>
                <small class="text-muted"><%= book.pagecount %> pages.</small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trades/edit.html.erb
<h1>Trade</h1>

<div class="card m-2" style="width: 18rem;">
  <div class="card-header"><%= @trade.book.title %></div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @trade.proposed_book.title %></li>
    <li class="list-group-item"><%= @trade.sender.username %></li>
    <li class="list-group-item"><%= @trade.status %></li>
  </ul>
</div>

<%= form_with model: [@book, @trade], local: true do |form| %>
  <%= form.hidden_field :sender_id %>
  <%= form.hidden_field :recipient_id %>
  <%= form.hidden_field :status, value: :waiting %>
  <p>
    <%= form.label :Status %>
    <%= form.select(:status, Trade.statuses.keys) %>
  </p>
  <p>
    <%= form.submit 'Respond' %>
  </p>
<% end %>


<%= link_to 'Back', dashboard_url %>

app/views/trades/show.html.erb
<div class="card m-2" style="width: 18rem;">
  <div class="card-header"><%= @trade.book.title %></div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @trade.proposed_book.title %></li>
    <li class="list-group-item"><%= @trade.sender.username %></li>
    <li class="list-group-item"><%= @trade.status %></li>
  </ul>
</div>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<h4><%= @user.email %></h4>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @user.books.each do |book| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-header"><%= book.title %></div>
            <div class="card-body">
              <p class="card-text">Written by <b><%= book.author %></b>.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Show', book_path(book), :class => "btn btn-sm btn-outline-secondary" %>
                </div>
                <small class="text-muted"><%= book.pagecount %> pages.</small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Back', root_path %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to Boox!</h1>
  <p class="lead">You can trade your books in here.</p>
  <hr class="my-4">
</div>

<h3>Here are some books.</h3>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @books.each do |book| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-header"><%= book.title %></div>
            <div class="card-body">
              <p class="card-text">Written by <b><%= book.author %></b>.</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted"><%= book.pagecount %> pages.</small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>